### PR TITLE
bats is available in homebrew

### PR DESCRIPTION
**Pull request by callahad**
Leaving ci on to make sure this doesn't break anything :)

### CODE REVIEW

**Comment by josegonzalez** [comment]
Good call. I do this for the official plugins: https://github.com/dokku/dokku-postgres/blob/master/Makefile

**Comment by callahad** [comment]
Makefiles are terrible at conditionals, especially when you start wanting to have three branches: Darwin, Ubuntu, and Debian... there *has* to be a better way. :)

Maybe calling out to an `install_deps.sh` script or something? Leaving that as an exercise for another time.

**Comment by josegonzalez** [comment]
@michaelshobbs might have some thoughts on that. Personally I prefer the makefile approach in this case.

**Comment by michaelshobbs** [comment]
@callahad agreed. However I figured this didn't need an external script since it's used in development and CI.

**Pull request merged**
