### PR TITLE
add MH to AUTHORS

### PR DESCRIPTION
**Pull request by michaelshobbs**
not sure if AUTHORS is kept up-to-date anymore but the instructions say I should add myself ;)

### CODE REVIEW

**Comment by josegonzalez** [comment]
I like how CI failed on this.

**Comment by michaelshobbs** [comment]
Wercker FTW!

**Comment by michaelshobbs** [comment]
seems like the CircleCI integration isn't happening and wercker still is? @progrium thoughts?

**Comment by josegonzalez** [comment]
He hasn't removed it from wercker yet so meh. We can merge.

**Pull request merged**
