### PR TITLE
Add links to official dokku datastorage plugins

### PR DESCRIPTION
**Pull request by josegonzalez**
Something that has been a long time coming, but here are official dokku datastores.

Note that all have been marked as beta (because they are!) and their implementations may change wildly. All plugins appear to work fine under docker 1.7. I plan on formalizing a release process for each, as well as guiding their development. 

All plugins use the official docker images, and I do not intend to change this. Their interface should stay the same, and in fact the diffs between each plugin should be quite minimal.

One thing I plan on noting in the documentation is that these datastores do not provide any sort of backup solution, and it is up to the developer to implement such a thing for their system (if their data is important enough).

All plugins roughly meet the spec proposed by @miraculixx in #854, with a few changes:

- Added a `service:unexpose` command, to remove any exposed ports.
- Added a `service:alias` command, which allows users to change the alias in use by a service.
- Changed `service:delete` to `service:destroy`, to match how the core works/
- Services store their data in `/var/lib/dokku/services/DATASTORE/SERVICE_NAME` instead of the home directory.
- Usage of the `docker-args` pluginhook instead of the `dokku:link` plugin, to reduce dependencies.

### Available datastore plugins

- [Elasticsearch](https://github.com/dokku/dokku-elasticsearch-plugin) [missing clone, connect, export, import]
- [MariaDB](https://github.com/dokku/dokku-mariadb-plugin)
- [Memcached](https://github.com/dokku/dokku-memcached-plugin) [missing clone, export, import]
- [Mongo](https://github.com/dokku/dokku-mongo-plugin)
- [MySQL](https://github.com/dokku/dokku-mysql-plugin)
- [Postgres](https://github.com/dokku/dokku-postgres-plugin)
- [RabbitMQ](https://github.com/dokku/dokku-rabbitmq-plugin) [missing clone, connect, export, import]
- [Redis](https://github.com/dokku/dokku-redis-plugin)
- [RethinkDB](https://github.com/dokku/dokku-rethinkdb-plugin) [missing clone, export, import]

### TODO:

- [x] Add [mongo](https://github.com/docker-library/docs/blob/master/mongo/README.md) plugin.
- [x] Add [rabbitmq](https://github.com/docker-library/docs/blob/master/rabbitmq/README.md) plugin.
- [x] Add [rethinkdb](https://github.com/docker-library/docs/blob/master/rethinkdb/README.md) plugin.
- [x] Finish implementation of `expose`/`unexpose`.
- [x] Ensure services come up on server reboot.
- [x] Document the services command structure and inner workings

Affexted existing datastore maintainers /cc @Kloadut @ohardy @hughfletcher @jlachowski @jeffutter @Flink @luxifer @sekjun9878 @robv @blag

### CODE REVIEW

**Comment by Flink** [comment]
@josegonzalez Great work it seems! :) There is a typo in your comment, the Postgres link points to the redis plugin.

So about community plugins, what does this mean exactly? I suppose they will be deprecated when those plugins won’t be in beta anymore?
Do you need help? Do we need (as current community plugins maintainers) to merge our work with yours?

**Comment by josegonzalez** [comment]
Fixed the typo.

I think that we should probably combine forces. If a community plugin maintainer wants to step up and help out with a particular plugin, then I'm all ears. If a developer wants to maintain their own, thats fine too.

The beta thing is there so that people don't instantly flock to them when they have working installations with the existing plugins.

**Comment by josegonzalez** [comment]
If any existing maintainer would like to join the team for a plugin they currently maintain, let me know and I will add you. I'd like to reduce the amount of work the you all are doing and provide a great experience for our community :)

**Comment by Flink** [comment]
@josegonzalez thanks, I just joined! :grin:
So yeah I think also that we should join forces ;) I’ll still maintain my own plugin for now but I could start to help on the postgres plugin.

How do we proceed?

**Comment by josegonzalez** [comment]
If you'd like to prototype any of the two remaining tasks on one of the plugins, that would be great. I can do the service writeup. Once that's all done, we merge this branch and are off to the races :)

**Comment by Flink** [comment]
Ok great. I’ll have to read/understand your code first so I won’t break anything :grin:
I’ll try to have something this week.

**Comment by michaelshobbs** [comment]
@josegonzalez love it man. I was just having the conversation about "official" datastore plugins on Friday with one of the Ops guys here.

**Comment by jeffutter** [comment]
Great work! I am really excited to have an official, supported plugin. I maintain one of the mongo and postgresql ones and I don't use them much anymore so it will be really great to have officially supported ones that have more eyes on them.

I would be glad to help maintain the official mongo and postgres ones. I can review code and partake in discussions. However, I don't think I will be using them enough to contribute much code.

**Comment by jeffutter** [comment]
Thanks! Also, from skimming the docs and the code. It looks like the official plugins support both ```n apps -> 1 db``` or ```1 app -> 1 db``` or ```n apps -> n dbs```. Correct? If so :+1:

**Comment by josegonzalez** [comment]
That is correct. Usage of the plugins is totally up to the user installing them. I hope that we stick to this for any further plugins, and that the only thing we do is allow users to easily customize their services :)

**Comment by josegonzalez** [comment]
Labeling this as `bc-break` as it will superscede all existing plugins and more or less force our users to use the latest docker, which might break other plugins.

**Comment by sekjun9878** [comment]
@josegonzalez Nice :D I'm guessing you would like us to put a redirect to the official dokku plugins for "combining forces"? I would be happy to contribute and provide feedback to the official repos, but I can't say I use it much anymore.

**Comment by hhff** [comment]
This is so great

**Comment by josegonzalez** [comment]
@sekjun9878 potentially. Once they get merged in, I would, though that's up to you :)

I'll add you to the repos when I'm in my office.

**Comment by josegonzalez** [comment]
I think the plugins are currently in a very good place. 

- All support both 0.3.x and 0.4.x dokku
- Well-tested
- Using latest versions of all datastores
- With few exceptions, implement every action that makes sense.

@Flink up to you when we want to tag a 1.0. We should talk about what that workflow looks like (and document it) but otherwise I'm quite comfortable with these plugins.

**Pull request merged**
