### PR TITLE
make sure dokku can read nginx logs and don't remove other perms

### LINKED ISSUE #1572: nginx:access-logs permission denied
clean install on a new virtual machine and things are running fine but the first time I ran `ssh -t dokku@dokku nginx:access-logs myapp -t` I got permission denied.

Further investigation shows the `/var/log/nginx` folder with `drwxr-x--- www-data adm` permissions, preventing the `dokku` user from accessing the folder.

I'm not sure what the "best" solution is here. If I just allow `+x` on the folder then inotify doesn't work with tail (it needs to be able to read the directory). So the folder probably needs to be changed to the dokku group or something else.

This is using ubuntu 14.04 LTS, dokku v0.4.2.

### PR DESCRIPTION
**Pull request by michaelshobbs**
- add current members of `adm` group to dokku group
- change group of `/var/log/nginx` (recursively) to `dokku`
- add group readable perm to everything in `/var/log/nginx`
- removes the check to bypass running `nginx:*-logs` commands as dokku 

closes #1572

### CODE REVIEW

**Comment by josegonzalez** [comment]
We need to document this so that users are aware of the adm change. We should probably add a new `logging` doc anyhow.

**Comment by michaelshobbs** [comment]
When you say "we" need to, are you going to update the docs?

**Comment by josegonzalez** [comment]
Yes.

**Comment by michaelshobbs** [comment]
Cool. Just wanted to clarify.

**Comment by michaelshobbs** [comment]
Need to make sure this doesn't break when running multiple times. I'll do that when I get back in front of a computer

**Comment by michaelshobbs** [comment]
:+1:

**Comment by mmerickel** [comment]
AFAICT this is not actually a fix because nginx's logrotate script switches new log files back to `www-data:adm` so unless that script is switched to `www-data:dokku` or dokku is added to the adm group this is still a problem.

Came back to work on Monday after logrotate and my access-log tail was busted again with permission denied.

**Comment by josegonzalez** [comment]
@mmerickel mind filing a bug?

**Comment by mmerickel** [comment]
Versus reopening #1572 I guess?

**Comment by josegonzalez** [comment]
Sure, I can do that. Commenting on a closed pr definitely wasn't going to help ;)

**Comment by mmerickel** [comment]
Fair enough!

**Pull request merged**
