### PR TITLE
Fix: appname was not correctly detected

### PR DESCRIPTION
**Pull request by alanjds**
Before the fix, the "most official" command line tool was detecting all my repos with "dokku" as the appname

### CODE REVIEW

**Comment by josegonzalez** [comment]
Looks like this change broke the client tests. What do your remotes look like?

**Comment by alanjds** [comment]
Follows my remotes.

```
airpill:apiregistro (master) alanjds$ uname -a
Darwin airpill 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
airpill:apiregistro (master) alanjds$ git --version
git version 1.9.3 (Apple Git-50)
airpill:apiregistro (master) alanjds$ git remote -v
deis	git@deis-01c.mydomain.com.br:hungry-universe.git (push)
deis	git@deis-01c.mydomain.com.br:hungry-universe.git (fetch)
dokku	dokku@dk-01.mydomain.com.br:apiregistro (push)
dokku	dokku@dk-01.mydomain.com.br:apiregistro (fetch)
heroku	git@heroku.com:apiregistro.git (fetch)
heroku	git@heroku.com:apiregistro.git (push)
stag	git@heroku.com:apiregistro-stag.git (push)
stag	git@heroku.com:apiregistro-stag.git (fetch)
airpill:apiregistro (master) alanjds$
```
And:
```
airpill:apiregistro (master) alanjds$ git remote -v 2>/dev/null | grep -Ei "dokku@$DOKKU_HOST" | head -n 1 | cut -f1 -d' ' | cut -f2 -d':' 2>/dev/null
dokku	dokku@dk-01.mydomain.com.br
airpill:apiregistro (master) alanjds$ git remote -v 2>/dev/null | grep -Ei "dokku@$DOKKU_HOST" | head -n 1 | cut -f1 -d' ' | cut -f3 -d':' 2>/dev/null
apiregistro
```

**Comment by josegonzalez** [comment]
How about instead it could be:

```
git remote -v 2>/dev/null | grep -Ei "dokku@$DOKKU_HOST" | head -n 1 | cut -f2 -d'@' | cut -f1 -d' ' | cut -f2 -d':' 2>/dev/null
```

That would cover both your case and the existing case I think.

**Comment by alanjds** [comment]
Is there. Waiting for Travis bless. Just realized that CircleCI is on the loop. I got confused. Anyway...

**Comment by josegonzalez** [comment]
We don't test via travis (if it's still enabled, ignore it).

**Comment by josegonzalez** [comment]
Awesome, does this work for you?

**Comment by alanjds** [comment]
Yes. It works. Thanks

**Pull request merged**
