### PR TITLE
Upgrade dokku installation to use docker-engine

### LINKED ISSUE #1295: upgrade to latest docker 1.7.0
Hello. I've tried to install dokku (commented out docker 1.6.2 installation, then `make install`) with official docker 1.7.0 pre-installed. It seems like it works.
So I request to update dokku to use docker 1.7.0.

### PR DESCRIPTION
**Pull request by josegonzalez**
Also simplify deb-based installation everywhere.

No idea yet if any of this works. I'll be trying it over the next few days...

Closes #1295
Closes #1461

### CODE REVIEW

**Comment by KernelMadness** [comment]
+1 to docker upgrade, in 1.8 they fixed annoying memory leak on log tail.
Currently it causes OOM to me.

**Comment by josegonzalez** [comment]
@michaelshobbs can you give this a once over? I can't really fix the package-based installation without merging/building a 0.4.0 package, but it should work fine.

**Comment by michaelshobbs** [comment]
How do you install a specific version of docker?

**Comment by josegonzalez** [comment]
You can't. And the new docker repo uses a new package name.

**Comment by michaelshobbs** [comment]
You absolutely can. It's inefficient but you can. I think we should allow for it like with did before with `$DOCKER_VERSION`.

```
$ curl -sSL https://get.docker.com/ | sh
$ dpkg -l | grep docker-engine
ii  docker-engine                       1.8.2-0~trusty                   amd64        Docker: the open-source application container engine
$ apt-cache madison docker-engine
docker-engine | 1.8.2-0~trusty | https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
docker-engine | 1.8.1-0~trusty | https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
docker-engine | 1.8.0-0~trusty | https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
docker-engine | 1.7.1-0~trusty | https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
docker-engine | 1.7.0-0~trusty | https://apt.dockerproject.org/repo/ ubuntu-trusty/main amd64 Packages
$ apt-get install docker-engine=1.7.0-0~trusty
$ dpkg -l | grep docker-engine
ii  docker-engine                       1.7.0-0~trusty                   amd64        Docker: the open-source application container engine
```

**Comment by josegonzalez** [comment]
You want to peg us to a specific version?

**Comment by michaelshobbs** [comment]
I think we should, no? So we can say dokku core 0.4.0 + official plugins run on docker version x.y.z but you can override that version with `$DOCKER_VERSION` when installing?

**Comment by josegonzalez** [comment]
Then upgrading docker would reinstall dokku if you install via deb package, no?

**Comment by michaelshobbs** [comment]
Can't we pin the deb dependency as well? I can take a swing at revising this PR if you want.

**Comment by josegonzalez** [comment]
Sure, pin the dependency if you want. Can we leave it open to anything in the 1.8.x line?

Feel free to update the PR.

**Comment by michaelshobbs** [comment]
It doesn't look like it's possible just with apt-get. We'd have to script around a bit. My thinking is that pinning would make troubleshooting a bit easier. Maybe not though? We weren't pinned before the 1.7.x change... I could be convinced it's not that big of a deal. Thoughts?

**Comment by michaelshobbs** [comment]
I would still like to be able to specify a version. I'll update to allow that at least.

**Comment by tilgovi** [comment]
You can use `apt-mark hold` but then you won't get the patch updates.

**Comment by michaelshobbs** [comment]
:+1:

**Comment by apmorton** [comment]
FYI, for anyone trying to install v0.3.26 currently, you just need to manually install herokuish 0.0.1 as follows before the dokku package will install properly
```apt-get install herokuish=0.0.1```

**Comment by josegonzalez** [comment]
Sorry about that, there was a snafu in releasing 0.4.0. We should be all good now!

**Pull request merged**
