### PR TITLE
Log user name and fingerprint in events

### PR DESCRIPTION
**Pull request by jazzzz**
This allows to see who is deploying.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Where does `NAME` come from?

**Comment by jazzzz** [comment]
> Where does NAME come from?

From `sshcommand`.

**Comment by josegonzalez** [comment]
I'm guessing it sets it as an environment variable, correct?

**Comment by jazzzz** [comment]
> I'm guessing it sets it as an environment variable, correct?

Yes, you can see this in `~dokku/.ssh/authorized_keys`.

**Pull request merged**
