### PR TITLE
use circleci for automated testing

### LINKED ISSUE #865: Migrate testing to CircleCI
Opening an issue to track progress and conversation.

### PR DESCRIPTION
**Pull request by michaelshobbs**
@progrium TODOs:
 - [x] follow project in CircleCI https://circleci.com/?join=dont-test-alone
 - [x] generate status api token https://circleci.com/docs/status-badges and send to @michaelshobbs
 - [x] setup irc notifications https://circleci.com/docs/configuration#notify

closes #865

### CODE REVIEW

**Comment by progrium** [comment]
Cool! So merge first then those things or merge after?

On Monday, January 5, 2015, Michael Hobbs <notifications@github.com> wrote:

> @progrium <https://github.com/progrium> TODOs:
> [] follow project in CircleCI https://circleci.com/?join=dont-test-alone
> [] generate status api token https://circleci.com/docs/status-badges and
> send to @michaelshobbs <https://github.com/michaelshobbs>
> [] setup irc notifications https://circleci.com/docs/configuration#notify
>
> closes #865 <https://github.com/progrium/dokku/issues/865>
> ------------------------------
> You can merge this Pull Request by running
>
>   git pull https://github.com/expa/dokku mh-circle-ci
>
> Or view, comment on, or merge it at:
>
>   https://github.com/progrium/dokku/pull/868
> Commit Summary
>
>    - try circle again
>    - attempt to use make install
>
> File Changes
>
>    - *A* circle.yml
>    <https://github.com/progrium/dokku/pull/868/files#diff-0> (29)
>    - *M* plugins/apps/pre-delete
>    <https://github.com/progrium/dokku/pull/868/files#diff-1> (2)
>    - *M* plugins/nginx-vhosts/dependencies
>    <https://github.com/progrium/dokku/pull/868/files#diff-2> (3)
>    - *M* tests/test_deploy
>    <https://github.com/progrium/dokku/pull/868/files#diff-3> (2)
>
> Patch Links:
>
>    - https://github.com/progrium/dokku/pull/868.patch
>    - https://github.com/progrium/dokku/pull/868.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/pull/868>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by josegonzalez** [comment]
I think you can do those first and then merge.

**Comment by michaelshobbs** [comment]
Yeah I'd like to include the build status badge in this PR

**Comment by josegonzalez** [comment]
@progrium bump :)

**Comment by progrium** [comment]
Okay, I believe I did them all.

On Tue, Jan 6, 2015 at 10:55 AM, Jose Diaz-Gonzalez <
notifications@github.com> wrote:

> @progrium <https://github.com/progrium> bump :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/pull/868#issuecomment-68913071>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by josegonzalez** [comment]
Did you send @michaelshobbs the token for the status badge?

**Comment by progrium** [comment]
Yes, via email.

On Tue, Jan 6, 2015 at 4:41 PM, Jose Diaz-Gonzalez <notifications@github.com
> wrote:

> Did you send @michaelshobbs <https://github.com/michaelshobbs> the token
> for the status badge?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/dokku/pull/868#issuecomment-68961206>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
Got it. I'm afk at the moment but I'll push this as soon as I get back.

**Comment by michaelshobbs** [comment]
I think we're good to go on this.

**Pull request merged**
