### PR TITLE
Require lxc-docker-1.6.2

### PR DESCRIPTION
**Pull request by josegonzalez**
1.7.0 Has issues with `docker ps` output, breaking all plugins

[ci-skip]

### CODE REVIEW

**Comment by michaelshobbs** [comment]
Can you also make this work for the dev env?

**Comment by josegonzalez** [comment]
^ That what you mean?

**Comment by michaelshobbs** [comment]
Boom!

**Comment by michaelshobbs** [comment]
any reason to hold up on merging this?

**Pull request merged**
