### PR TITLE
document deploying private git submodules. closes #644

### LINKED ISSUE #644: private git submodule fails
I'm trying to deploy a repo with a private submodule. It fails of course.
```
git push dokku@localhost:dokku.example.com master
Counting objects: 8, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 655 bytes, done.
Total 6 (delta 3), reused 4 (delta 1)
-----> Cleaning up ...
-----> Building dokku.example.com ...
remote: HEAD is now at 2e28837... submodule for testing
remote: Host key verification failed.
remote: fatal: The remote end hung up unexpectedly
remote: Clone of 'git@github.com:example/nodecore' into submodule path 'nodecore' failed
To dokku@localhost:dokku.example.com
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@localhost:dokku.example.com'
```

I've read progrium/dokku#314. However, embedding the username and password in the repo is not an option. 

I'm running both [dokku-deployment-keys](https://github.com/cedricziel/dokku-deployment-keys) and [dokku-hostkeys-plugin](https://github.com/cedricziel/dokku-hostkeys-plugin). So, at first glance, I figured we just needed to run these plugins before the app gets built. Unfortunately there is currently no way of doing this. See [here](https://github.com/progrium/dokku/blob/master/dokku#L32-L37). 

So, one approach might be to break lines 33-35 into a new built-in plugin and subsequently move the aforementioned key plugins into a new phase that is called by the build-in.

Thoughts on this? Is this interesting to anyone else or am I off my rocker?

### PR DESCRIPTION
**Pull request by michaelshobbs**
closes #644

### CODE REVIEW

**Comment by josegonzalez** [comment]
+1. Can you do a ci-skip and also ref the issue?

**Comment by michaelshobbs** [comment]
its ref'd in the comments. yeah meant to skip ci.

**Comment by josegonzalez** [comment]
It's not ref'd in the commit message...

**Comment by michaelshobbs** [comment]
Ah haha! We've not been consistently doing that it seems. Perhaps a CONTRIBUTING.md readme should happen.

**Pull request merged**
