### PR TITLE
use column to format help output

### PR DESCRIPTION
**Pull request by michaelshobbs**
Example with plugin that has not updated its help output:

```
# dokku
Usage: dokku [--quiet|--trace|--rm-container|--rm|--force] COMMAND <app> [command-specific-options]

Options:
    apps:create <app>                                                                                                    Create a new app
    apps:destroy <app>                                                                                                   Permanently destroy an app
    apps                                                                                                                 List your apps
    backup:export [file]                                                                                                 Export dokku configuration files
    backup:import [file]                                                                                                 Import dokku configuration files
    config (<app>|--global)                                                                                              Display all global or app-specific config vars
    config:get (<app>|--global) KEY                                                                                      Display a global or app-specific config value
    config:set (<app>|--global) KEY1=VALUE1 [KEY2=VALUE2 ...]                                                            Set one or more config vars
    config:unset (<app>|--global) KEY1 [KEY2 ...]                                                                        Unset one or more config vars
    docker-options:add <app> <phase(s)> OPTION                                                                           Add docker option to app for phase (comma seperated phase list)
    docker-options <app>                                                                                                 Display apps docker options for all phases
    docker-options <app> <phase(s)>                                                                                      Display apps docker options for phase (comma seperated phase list)
    docker-options:remove <app> <phase(s)> OPTION                                                                        Remove docker option from app for phase (comma seperated phase list)
    domains:add <app> DOMAIN                                                                                             Add a custom domain to app
    domains <app>                                                                                                        List custom domains for app
    domains:clear <app>                                                                                                  Clear all custom domains for app
    domains:remove <app> DOMAIN                                                                                          Remove a custom domain from app
    events:list                                                                                                          List logged events
    events:off                                                                                                           Disable events logger
    events:on                                                                                                            Enable events logger
    events [-t]                                                                                                          Show the last events (-t follows)
    help                                                                                                                 Print the list of commands
    hostkeys:app:add <app>                          Add a app-specific hostkey
    hostkeys:app:autoadd <app> <hostname>           Automatically add hostkeys for a given host to the shared hostkeys
    hostkeys:app:delete <app>                       Deletes all app-specific hostkeys
    hostkeys:app:show <app>                         Show all hostkeys for a given app
    hostkeys                                        Print an explanation (Useful to get the concept)
    hostkeys:shared:add                             Add a shared hostkey
    hostkeys:shared:autoadd <hostname>              Automatically add hostkeys for a given host to the shared hostkeys
    hostkeys:shared:delete                          Deletes all shared hostkeys
    hostkeys:shared:delete <hostname>               Deletes the shared hostkeys for the given host
    hostkeys:shared:show                            Show shared hostkeys
    logs <app> [-t]                                                                                                      Show the last logs for an application (-t follows)
    ls                                                                                                                   Pretty listing of deployed applications and containers
    nginx:build-config <app>                                                                                             (Re)builds nginx config for given app
    nginx:import-ssl <app>                                                                                               Imports a tarball from stdin; should contain server.crt and server.key
    plugins-install                                                                                                      Install active plugins
    plugins                                                                                                              Print active plugins
    plugins-update                                                                                                       Update active plugins
    ps <app>                                                                                                             List processes running in app container(s)
    ps:rebuildall                                                                                                        Rebuild all apps
    ps:rebuild <app>                                                                                                     Rebuild an app
    ps:restartall                                                                                                        Restart all deployed app containers
    ps:restart <app>                                                                                                     Restart app container(s)
    ps:scale <app> <proc>=<count> [<proc>=<count>]                                                                       Set how many instances of a given process to run
    ps:start <app>                                                                                                       Start app container(s)
    ps:stop <app>                                                                                                        Stop app container(s)
    run <app> <cmd>                                                                                                      Run a command in the environment of an application
    shell                                                                                                                Spawn dokku shell
    url <app>                                                                                                            Show the first URL for an application (compatibility)
    urls <app>                                                                                                           Show all URLs for an application
    version                                                                                                              Print dokku's version
```

### CODE REVIEW

**Comment by michaelshobbs** [comment]
@josegonzalez you're welcome :stuck_out_tongue_winking_eye:

**Comment by josegonzalez** [comment]
Does this break plugin help output?

**Comment by michaelshobbs** [comment]
What do you mean? It works in my test env.

**Comment by josegonzalez** [comment]
What about a space character? And then somehow trim whitespace from the second column?

**Comment by michaelshobbs** [comment]
There's white space throughout the entire line though....

**Comment by josegonzalez** [comment]
Well won't column only take the first whitespace? Maybe something like `cut` would work better?

**Comment by michaelshobbs** [comment]
if you take the following as an example, you have white space in the first section and whitespace in second section but I see no common way to delineate from line to line.

```
    events [-t]                                                Show the last events (-t follows)
    help                                                       Print the list of commands
    logs <app> [-t]                                            Show the last logs for an application (-t follows)
    ls                                                         Pretty listing of deployed applications and containers
    nginx:build-config <app>                                   (Re)builds nginx config for given app
```

**Comment by josegonzalez** [comment]
Dammit. I guess this is a breaking change then

**Comment by michaelshobbs** [comment]
I'll need to update docs to include this format too

**Comment by josegonzalez** [comment]
Closes #1347.

**Comment by jpscharf** [comment]
This change should be BC, if the help command does not have the comma, it should just print as is:
> [test-dokku-help-format.sh](https://gist.github.com/jpscharf/8c3cf4cc77eb121b222b)

**Input**
```
new-help,Print the list of commands
new-plugins,Print active plugins
new-plugins-install,Install active plugins
new-plugins-update,Update active plugins
old-help                Print the list of commands
old-plugins             Print active plugins
old-plugins-install     Install active plugins
old-plugins-update      Update active plugins
```

**Output**
```
new-help                                            Print the list of commands
new-plugins                                         Print active plugins
new-plugins-install                                 Install active plugins
new-plugins-update                                  Update active plugins
old-help                Print the list of commands
old-plugins             Print active plugins
old-plugins-install     Install active plugins
old-plugins-update      Update active plugins
```

**Comment by michaelshobbs** [comment]
@jpscharf fair point. i'll update this

**Comment by michaelshobbs** [comment]
@josegonzalez tested with a different plugin and it still works. just looks unaligned as @jpscharf showed

**Comment by josegonzalez** [comment]
Are there any plugins with a comma in the definition already?

**Comment by michaelshobbs** [comment]
That's a good question. Any suggestions on how to find this out?

**Comment by josegonzalez** [comment]
Install all the plugins and type "dokku help" :P

**Comment by michaelshobbs** [comment]
Let me know how that goes....

**Comment by josegonzalez** [comment]
lmao fine merge at will

**Comment by michaelshobbs** [comment]
Honestly, if any already do, it's just the alignment that will be off. I don't think it's a big deal.

**Pull request merged**
