### PR TITLE
Add official redirect plugin

### LINKED ISSUE #924: Redirects as a built-in feature
Hey,

Thanks for this great tool! I just saw that domain management is now a built-in feature of dokku, no need to use dokku-domains-plugin anymore. That's great to hear. But one important feature I think pretty much websites implement is redirect: non-www <-> www is required these days. We can do it using dokku-redirects-plugin, but as you implemented domains I thought you could also implement redirects.

Cheers.

### PR DESCRIPTION
**Pull request by Flink**
Closes #924

### CODE REVIEW

**Comment by josegonzalez** [comment]
`[ci skip]` is your documentation friend :)

**Comment by michaelshobbs** [comment]
👍🏼👊🏼

**Comment by Flink** [comment]
@josegonzalez yep sorry, I’m always forgetting this one :grin:

**Comment by josegonzalez** [comment]
@Flink might be a good idea to move the non-official one to "deprecated" or something :P

**Comment by josegonzalez** [comment]
Same for any others that you've covered so far.

**Comment by Flink** [comment]
Yeah but I didn’t make a redirect plugin before. So I’m not sure about deprecating plugins I don’t own :grin:

**Comment by josegonzalez** [comment]
Fair enough. We'll keep it for now.

**Pull request merged**
