### PR TITLE
Resolve SC2145: 'Argument mixes string and array.'

### PR DESCRIPTION
**Pull request by callahad**
https://github.com/koalaman/shellcheck/wiki/SC2145

### CODE REVIEW

**Comment by callahad** [comment]
Wait on merging this one -- need to double check the printf behavior

**Comment by callahad** [comment]
OK, commit 84c0988 looks good for this.

```bash
$ cat ./sc2145.sh
#!/usr/bin/env bash

a() {
  printf "%-25s %-25s %-25s %-25s\n" "-----> $@"
}

b() {
  printf "%-6s %-18s %-25s %-25s %-25s\n" "----->" "$@"
}

a "foo" "bar" "baz" "qux"
b "foo" "bar" "baz" "qux"

$ ./sc2145.sh
-----> foo                bar                       baz                       qux
-----> foo                bar                       baz                       qux
```

**Comment by callahad** [comment]
（╯°□°）╯︵ ┻━┻

```
remote: -----> Building test-config-1942 from herokuish...
remote: WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
To dokku@dokku.me:test-config-1942
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@dokku.me:test-config-1942'
+ failed git-push
+ echo '************ git-push failed ************'
************ git-push failed ************
```

**Comment by callahad** [comment]
（╯°□°）╯︵ ┻━┻

```
not ok 43 (core) port exposure (xip.io style hostnames)
...
# curl: (6) Could not resolve host: my-cool-guy-test-app.127.0.0.1.xip.io
```

Between both CI runs for this PR, (1547)[https://circleci.com/gh/progrium/dokku/1547] and (1550)[https://circleci.com/gh/progrium/dokku/1550], everything has actually passed.

Should we just merge it?

**Comment by josegonzalez** [comment]
My policy is to merge failing PRs only when there is a doc change. All others require a re-run.

**Comment by callahad** [comment]
Works for me :)

**Pull request merged**
