### PR TITLE
expose the port for `dokku run $APP /bin/bash`

### PR DESCRIPTION
**Pull request by MatthewMueller**
Super useful for debugging. So if you run `docker ps`:

```
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS                      NAMES
b55e977cbcd0        dokku/$APP:latest          "/exec /bin/bash"      6 seconds ago       Up 5 seconds        0.0.0.0:49176->5000/tcp    berserk_stallman
```

### CODE REVIEW

**Comment by josegonzalez** [comment]
@MatthewMueller We can pass a second argument to the `docker-args` pluginhook with the command being run, which would allow you to do this. I'll open a PR for that.

**Comment by josegonzalez** [comment]
@MatthewMueller Closing as there is an alternative PR that should allow you to easily build a plugin to do what you need to do, without potentially exposing this configuration to in production.

**Comment by MatthewMueller** [comment]
much better! thanks!

**Comment by MatthewMueller** [comment]
@josegonzalez can you provide a usage example?

**Comment by josegonzalez** [comment]
Create a plugin with a `docker-args` command and have it output your args.

```shell
#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat); APP="$1"; CMD="$2"
EXPOSE_PORT=$(dokku config:get $APP EXPOSE_PORT);

if [ "$CMD" == "run" ] && [ "$EXPOSE_PORT" == "1" ]; then 
  output="-p 5000 -e PORT=5000"
fi

echo "$STDIN $output "
```

**Pull request closed without merging**
