### PR TITLE
Strip the `dokku-` part from plugins on install

### PR DESCRIPTION
**Pull request by Flink**
This way we won’t have a list of plugins with a lot of `dokku-*` in their names.

### CODE REVIEW

**Comment by michaelshobbs** [comment]
I totally get the reasoning here but I'm not sure we want to 'magically' modify names of plugins. I'm curious if anybody else has thoughts on this. 

(To be clear: I don't think I personally care but I'd like to hear what other users think before merging this in)

**Comment by hhff** [comment]
jah i tend to agree - with such a large mass of bash scripting I think we'd want to keep the "magic" to a minimum

**Comment by josegonzalez** [comment]
You could ask people for confirmation and respect the `--force` flag.

**Comment by Flink** [comment]
@josegonzalez ask for confirmation of installation without the `dokku-` part? What the `--force` flag will do ?

**Comment by josegonzalez** [comment]
A few things:

- We should be able to specify the plugin name.
- If we detect a `dokku-` prefix, we should ask the user to confirm that they want to remove it.
- If the user does `dokku --force plugin:install whatever`, then it will remove the prefix without prompting the user.

**Comment by Flink** [comment]
Ok so `plugin:install` should accept a second argument that specify the local name of the plugin to be installed, right?
If user provides this second argument, do we strip the `dokku-` prefix if it has it? I think we shouldn’t in this case.
And then `--force` should do nothing when user provide the second argument in this case.

**Comment by josegonzalez** [comment]
We don't strip if they provide a name.

**Comment by michaelshobbs** [comment]
I'd prefer if we didn't prompt by default. Sounds annoying

**Comment by josegonzalez** [comment]
Okay, fine by me.

**Comment by Flink** [comment]
Ok, so `--force` is not needed anymore then :)

**Comment by Flink** [comment]
Updated :)

**Comment by josegonzalez** [comment]
Seems legit!

**Pull request merged**
