### PR TITLE
corrected README.md's ref to bootstrap.sh URL

### PR DESCRIPTION
**Pull request by edm00se**
The URL w/ raw.github.com wasn't working for me, clicking the raw link in GH's repo led me [https://raw.githubusercontent.com/progrium/dokku/master/bootstrap.sh](https://raw.githubusercontent.com/progrium/dokku/master/bootstrap.sh), which is working; so I updated the URL.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you revert the change to `master`? We definitely still want to peg to a specific version.

**Comment by edm00se** [comment]
Reverted as requested, my bad.

**Comment by josegonzalez** [comment]
Thanks for the pr!

**Comment by edm00se** [comment]
My pleasure!

**Pull request merged**
