### PR TITLE
disable VHOST deployment if global VHOST file is missing and an app domain has not been added

### LINKED ISSUE #879: Wrong app URL when no VHOST file exists
**Problem:**

If you delete the VHOST file because you want to use port-based deployment (i.e. you're installing dokku in a VM), I expect the application to be deployed at http://`hostname`:`port` as per documentation.
But the current release deploys the app on http://`app-name`.`hostname`, ignoring the fact that no VHOST is set.

**Steps to reproduce:**

1) Install dokku
2) Remove /home/dokku/VHOST
3) Deploy sample node-js-app
4) In the git push output you'll see

    =====> Application deployed:
    http://node-js-app.<hostname>

**Expected outcome:**

    =====> Application deployed:
    http://<hostname>:<port>

**Possible fix:**

`dokku url node-js-app` returns the wrong hostname although the logic is correct.
The issue is in `dokku nginx:build-config node-js-app` as the logic to deploy on a port is executed only when the NO_VHOST variable is set (https://github.com/progrium/dokku/blob/master/plugins/nginx-vhosts/commands#L32)

Setting it manually works as expected:

    root@combotest:~# env NO_VHOST=1 dokku nginx:build-config node-js-app
    -----> NO_VHOST set, deleting node-js-app/VHOST
    -----> NO_VHOST set, deleting nginx.conf
    -----> NO_VHOST set, reloading nginx after nginx.conf deletion

I suspect this NO_VHOST variable should be set after deploy before calling nginx:build-config, but it isn't.

If you can point out which is the best place to set this variable, I can do a pull request myself.

### PR DESCRIPTION
**Pull request by michaelshobbs**
closes #879

### CODE REVIEW

**Comment by josegonzalez** [comment]
If a user manually set a domain via the domains plugin, do we want to disable vhosts then?

**Comment by michaelshobbs** [comment]
Fair point. If the answer is no, then this whole feature need some refactoring I think...

**Comment by josegonzalez** [comment]
If a user uses the domains plugin, that should mean that the app has a vhost. Is that the case with this plugin?

**Comment by michaelshobbs** [comment]
I have something that I think works under that assumption. Writing tests now.

**Comment by michaelshobbs** [comment]
So this update will use a port based deployment if there is no global VHOST and no app vhost but is less aggressive when turning off VHOST support. So you can add a domain even if you have no global VHOST

**Pull request merged**
