### PR TITLE
silent grep stderr. closes #862

### LINKED ISSUE #862: tests.mk being invoked during installation
Seems line 42 is being invoked when calling `make install`. This is the line:

```
ifeq ($(shell grep dokku.me /home/dokku/VHOST),)
```

And here is how I know:

```
==> default: stdin: is not a tty
==> default: grep:
==> default: /home/dokku/VHOST
==> default: : No such file or directory
==> default: wget -qO /usr/local/bin/sshcommand https://raw.github.com/progrium/sshcommand/master/sshcommand
```

That happens right at the start of the install :(

@michaelshobbs assigning to you since you originally setup the test integration.

### PR DESCRIPTION
**Pull request by michaelshobbs**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Heh, troll.

**Comment by michaelshobbs** [comment]
:smile: opening a PR is just a habit

**Comment by josegonzalez** [comment]
Oh thats fine, I meant the fix.

Note: I'd like to continue working through PRs. Helps everyone get familiar with whats going on/raise objections before it goes into master. Plus, it makes doing releases easier; I only need to look at the "merge pull request" commits to see what should go in the changelog :)

**Comment by michaelshobbs** [comment]
That was option 1 :smile:

**Pull request merged**
