### PR TITLE
Fix URLs for docu/ links

### PR DESCRIPTION
**Pull request by frdmn**
I noticed that the links point to a non existent "dokku/" folder.

PR should update said links to the current/proper ones :)

### CODE REVIEW

**Comment by josegonzalez** [comment]
Thanks for the pr!

**Comment by josegonzalez** [comment]
Oh, this is meant to be browsed from the docs site, not from inside the repo. Thats why the links seemed broken. Going to revert this.

**Comment by frdmn** [comment]
Ah crud, my bad! I just checked via GitHub and noticed that they all ended up in 404's.

**Comment by josegonzalez** [comment]
Yeah. If I can figure out how to get viewdocs into circleci, I might be able to get @progrium to turn on auto-deploys for it, at which point I can take a stab at rewriting urls like that...

**Pull request merged**
