### PR TITLE
Added unofficial Nats plugin to plugins.md

### PR DESCRIPTION
**Pull request by byrnedo**
Added plugin for Nats message queue (http://nats.io) to docs.

### CODE REVIEW

**Comment by josegonzalez** [comment]
@byrnedo fancy. I see you copied most of the dokku core stuff. Anything that is missing from your plugins that is in the core ones? Would be cool to make it official (you can keep maintaining it of course!)

**Comment by byrnedo** [comment]
I have you in the license notice :)

Yeah I pretty much copied the redis plugin. I can check if anything's missing but I did remove the 'connect', 'import', 'export' and 'clone ? or was that copy' commands. Yeah I was thinking maybe you'd be interested in making it official? I'd be happy to maintain

**Comment by josegonzalez** [comment]
I added you to the dokku org, please initiate the transfer of the project over and we'll get everything setup :)

**Comment by byrnedo** [comment]
done and thanks :)

**Comment by josegonzalez** [comment]
Please go through and update the plugin settings etc. to match the other plugins :) Thanks for everything!

**Comment by byrnedo** [comment]
ok will do!

**Comment by josegonzalez** [comment]
@byrnedo you may need to make a new PR to this repo to fix the links :)

**Comment by byrnedo** [comment]
yeah, I'll move it up into official plugins too.

:ok_hand:

**Pull request merged**
