### PR TITLE
support dockerfiles without expose command. closes #1083

### LINKED ISSUE #1083: pre-receive hook declined - Dockerfile with no EXPOSE ports
Trying to push a worker app that's Dockerfile based and doesn't expose any ports results in a pre-receive hook declined. Here's the relevant (i think) trace output:

```
-----> Building worker from dockerfile...
remote: + [[ -f /home/dokku/dokkurc ]]
remote: ++ docker images -f dangling=true -q
remote: + [[ -d /home/dokku/.dokkurc ]]
remote: + for f in '$DOKKU_ROOT/.dokkurc/*'
remote: + source /home/dokku/.dokkurc/DOKKU_TRACE
remote: ++ export DOKKU_TRACE=1
remote: ++ DOKKU_TRACE=1
remote: + [[ -n 1 ]]
remote: + set -x
remote: + parse_args build worker dockerfile /tmp/tmp.m8ykGDSWXy
remote: + for arg in '"$@"'
remote: + case "$arg" in
remote: + for arg in '"$@"'
remote: + case "$arg" in
remote: + for arg in '"$@"'
remote: + case "$arg" in
remote: + for arg in '"$@"'
remote: + case "$arg" in
remote: + return 0
remote: + args=("$@")
remote: + [[ build =~ ^--.* ]]
remote: + has_tty
remote: ++ docker ps -a -f status=exited -q
remote: ++ /usr/bin/tty
remote: ++ true
remote: + [[ not a tty == \n\o\t\ \a\ \t\t\y ]]
remote: + return 1
remote: + DOKKU_QUIET_OUTPUT=1
remote: ++ id -un
remote: + [[ dokku != \d\o\k\k\u ]]
remote: + [[ -n '' ]]
remote: + case "$1" in
remote: + implemented=0
remote: + for script in '$PLUGIN_PATH/*/commands'
remote: + set +e
remote: + /var/lib/dokku/plugins/00_dokku-standard/commands build worker dockerfile /tmp/tmp.m8ykGDSWXy
remote: ++ dirname /var/lib/dokku/plugins/00_dokku-standard/commands
remote: + source /var/lib/dokku/plugins/00_dokku-standard/../common/functions
remote: ++ set -eo pipefail
remote: ++ [[ -n 1 ]]
remote: ++ set -x
remote: + case "$1" in
remote: + APP=worker
remote: + IMAGE=dokku/worker
remote: + IMAGE_SOURCE_TYPE=dockerfile
remote: + TMP_WORK_DIR=/tmp/tmp.m8ykGDSWXy
remote: + CACHE_DIR=/home/dokku/worker/cache
remote: + pushd /tmp/tmp.m8ykGDSWXy
remote: + case "$IMAGE_SOURCE_TYPE" in
remote: ++ awk '{ print $2 }'
remote: ++ head -1
remote: ++ grep EXPOSE Dockerfile
remote: + DOCKERFILE_PORT=
remote: + exit_code=1
remote: + set -e
remote: + '[' 1 -eq 10 ']'
remote: + implemented=1
remote: + '[' 1 -ne 0 ']'
remote: + exit 1
remote: + docker rm
remote: + docker rmi
remote: + exit_code=1
remote: + set -e
remote: + '[' 1 -eq 10 ']'
remote: + implemented=1
remote: + '[' 1 -ne 0 ']'
remote: + exit 1
remote: + exit_code=1
remote: + set -e
remote: + '[' 1 -eq 10 ']'
remote: + implemented=1
remote: + '[' 1 -ne 0 ']'
remote: + exit 1
remote: + exit_code=1
remote: + set -e
remote: + '[' 1 -eq 10 ']'
remote: + implemented=1
remote: + '[' 1 -ne 0 ']'
remote: + exit 1
+ exit_code=0
+ set -e
+ '[' 0 -eq 10 ']'
+ implemented=1
+ '[' 0 -ne 0 ']'
+ for script in '$PLUGIN_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/nginx-vhosts/commands git-receive-pack ''\''worker'\'''
++ dirname /var/lib/dokku/plugins/nginx-vhosts/commands
+ source /var/lib/dokku/plugins/nginx-vhosts/../common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ case "$1" in
+ exit 10
+ exit_code=10
+ set -e
+ '[' 10 -eq 10 ']'
+ continue
+ for script in '$PLUGIN_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/postgresql/commands git-receive-pack ''\''worker'\'''
+ exit_code=0
+ set -e
+ '[' 0 -eq 10 ']'
+ implemented=1
+ '[' 0 -ne 0 ']'
+ for script in '$PLUGIN_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/ps/commands git-receive-pack ''\''worker'\'''
++ dirname /var/lib/dokku/plugins/ps/commands
+ source /var/lib/dokku/plugins/ps/../common/functions
++ set -eo pipefail
++ [[ -n 1 ]]
++ set -x
+ case "$1" in
+ exit 10
+ exit_code=10
+ set -e
+ '[' 10 -eq 10 ']'
+ continue
+ for script in '$PLUGIN_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/redis/commands git-receive-pack ''\''worker'\'''
+ exit_code=0
+ set -e
+ '[' 0 -eq 10 ']'
+ implemented=1
+ '[' 0 -ne 0 ']'
+ for script in '$PLUGIN_PATH/*/commands'
+ set +e
+ /var/lib/dokku/plugins/shell/commands git-receive-pack ''\''worker'\'''
+ case "$1" in
+ exit 10
+ exit_code=10
+ set -e
+ '[' 10 -eq 10 ']'
+ continue
+ '[' 1 -eq 0 ']'
+ exit 0
To dokku@lapwinglabs.com:worker
 ! [remote rejected] master -> master (pre-receive hook declined)
```

Is this a bug, or just an unsupported use case?

### PR DESCRIPTION
**Pull request by michaelshobbs**
includes tests

closes #1083

### CODE REVIEW

**Comment by josegonzalez** [comment]
This makes me think that we should look into what it means to have a working background app. What does that check look like? How does that change the checks plugin?

**Comment by josegonzalez** [comment]
Note: this can be merged before we discuss that. I think a revamped `checks` plugin can come for a 0.4.0 or above release.

**Comment by michaelshobbs** [comment]
Yeah makes sense. I have a use case where I'm deploying an app that contains background workers in a separate "stack" that doesn't get web traffic but still deploys the web app so that CHECKS pass.

**Comment by bdentino** [comment]
if it helps, here's my use case:

i have a redis-backed task queue, with a web application in a separate container that adds tasks periodically. alongside that I have a worker app that links to redis and does nothing but pull tasks as they become available and run them in the background. when i have more tasks than one worker can handle I spin up more instances.

**Comment by josegonzalez** [comment]
@bdentino not saying we're not merging this - we will once tests pass - I'm more saying that we need to start getting more serious about non-web applications and how we treat them. 

For instance, the checks plugin is useful for testing that a web app works, but what can we do to make that work for background workers? Maybe allow specifying checking for a process running for a certain amount of time? Tailing logs for a message saying "all good"? etc. Just trying to think of a way to make the dokku deployment process as smooth as butter for our users :)

**Pull request merged**
