### PR TITLE
Nginx configuration for running behind load balancer

### PR DESCRIPTION
**Pull request by assaf**
When running behind a load balancer that terminates SSL connections (e.g. AWS ELB), Nginx must pass the X-Forwarded headers from the load balancer to the application.

When Nginx is terminating SSL connections, it must not trust any headers sent from the client, and must set those directly.

This PR adds a new setting `DOKKU_SSL_TERMINATED` that, when set, will pick the Nginx configuration that supports a load balancer that terminates SSL connections.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you add documentation for this feature?

**Comment by assaf** [comment]
Added documentation.

Right now I'm calling this flag `DOKKU_SSL_TERMINATED` since it evolved from our specific use case, but clearly not the best term, so ideas on what to call this?

**Comment by josegonzalez** [comment]
Sorry for the wait, but can you rebase this? I think the env var naming is good as is, and docs make it clear as to how this is expected to work. I'll merge once rebased :)

**Comment by assaf** [comment]
This will have to wait util next week, I'll pull what ever is in master, fix & rebase as necessary.

**Comment by josegonzalez** [comment]
Closing in favor of #1470. Thanks for your work @assaf!

**Pull request closed without merging**
