### PR TITLE
remove docker restart policy until it stabilizes

### LINKED ISSUE #1505: New containers created every reboot
Description of problem:

A new docker container is created every time I reboot the machine for Dokku apps.

Output of the following commands

- `dokku version`:
```
v0.4.0
```
- `dokku plugins`:
```
 !     `plugins` is not a dokku command.
 !     See `dokku help` for a list of available commands.
```
- `docker version`:
```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```
- `docker info`:
```
Containers: 5
Images: 9
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 1
Total Memory: 993.2 MiB
Name: dokku
ID: F5XJ:RPWM:PSSQ:OY32:XEHY:TQ6C:YYJQ:K4WG:O4SP:QUA7:63LM:JNHQ
WARNING: No swap limit support
```
- `uname -a`:
```
Linux dokku 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Environment details (AWS, VirtualBox, physical, etc.):

Running Dokku on a clean VirtualBox machine with a clean Ubuntu Server 14.04.3 LTS install. 
How was dokku installed?:
```
$ history
    1  sudo apt-get update
    2  sudo apt-get upgrade
    3  wget https://raw.github.com/progrium/dokku/v0.4.0/bootstrap.sh
    4  sudo DOKKU_TAG=v0.4.0 bash bootstrap.sh
    5  sudo sshcommand acl-add dokku bob
        ...
```
How reproducible:
I just did this a second time to make sure it wasn't some mistake:
* Create a new virtual machine in VirtualBox.
* Install Ubuntu Server 14.04.3 LTS with OpenSSH server.
* Run commands above to update/upgrade and install dokku.
* Push NodeJS application to `dokku@dokku.local:cycle-remote`
* Check `sudo docker ps` and verify one container is running.
* `sudo reboot`
* Check `sudo docker ps` again and notice there are 2 containers running.

Actual Results:

More reboots results in more *running* containers!

Expected Results:

The same container that was initially started should be running after rebooting.

Additional info:

I did notice that no web-based installer was started nor was it available on http://dokku.local/. http://dokku.local/ only showed the default nginx page after installing Dokku.

Additionally after pushing my app to `cycle-remote` (or `cycleremote`) I couldn't access the app through http://cycle-remote.dokku.local/ or http://cycle-remote.dokku.local/. I noticed NO_VHOST was set to 1, so I used `dokku config:unset cycle-remote NO_VHOST`. This still did not bring up the mentioned urls. Only after issueing `dokku domains:add cycle-remote cycle-remote.dokku.local` did the url come up. I presume this is unrelated to the issue I'm submitting, but I thought I'd mention this.

### PR DESCRIPTION
**Pull request by michaelshobbs**
closes #1505

### CODE REVIEW

**Comment by beverku** [comment]
Is it time to look into the restart policy again with docker 1.9.x out?  Add a new unless-stopped restart policy (#15348) was added in 1.9.0

**Comment by josegonzalez** [comment]
If you want to replicate this by using the official `docker-options` plugin and letting us know if it worked, that would be A+.

**Comment by beverku** [comment]
Sure, I will try that out as soon as I get a chance, it will probably be a day or two.

**Comment by josegonzalez** [comment]
cool :)

**Comment by beverku** [comment]
OK, I was able to test out the ```docker-option --restart=unless-stopped```.  Based on the testing that I have performed this behaves as I would desire.  

Below is a summary of my testing:
I have a test-app deployed with DOKKU_SCALE=2

```
    dokku docker-options:add test-app deploy --restart=unless-stopped
    sudo reboot
```

After setting the restart option following any reboot I would see the following behavior:
* The initial ```docker ps``` shows 4 containers up.
* After a couple of minutes it shows only the 2 expected containers up.

```docker inspect``` showed for both containers:
```json
"RestartPolicy": {
            "Name": "unless-stopped",
            "MaximumRetryCount": 0
        }
```


After causing the app to crash (process.exit(1)) each container twice:
```docker inspect``` showed for both containers:
```json 
"RestartCount": 2
```


Then ```sudo reboot```
* See reboot behavior description above.


Execute ```dokku ps:restart test-app``` 3 Times in quick succession:
* ```docker ps``` Shows 8 containers up for 1-2 minutes
* Then back down to expected 2


Then ```sudo reboot```
* See reboot behavior description above.


Then ```dokku ps:stop test-app```
* ```docker ps``` shows no containers running

Then ```sudo reboot```
* This time only two containers come up.  
* This is the same as doing a ```ps:stop``` and reboot with an app that does not have the restart policy.



Push new version of the test-app
* Behaves the same as the reboot behavior description above.
* ```docker inspect``` shows that the RestartPolicy is retained for both containers.


Test crash the test-app 
* the containers are still restarted


Then ```sudo reboot```
* Same reboot behavior described above

**Comment by josegonzalez** [comment]
What happens on memory-constrained systems? Can you try this on a box with 512mb ram and 512mb swap?

**Comment by michaelshobbs** [comment]
Might I suggest bringing this conversation to a new issue?

**Comment by josegonzalez** [comment]
:+1:

**Pull request merged**
