### PR TITLE
Add `dokku enter` for connecting to an app container

### LINKED ISSUE #1332: RFC - Implement a dokku enter command
I don't know if it was previously discussed but what about and `dokku enter <name> [bash]` command that allow the admin to easly enter a running container using `bash`.

I often have the need to enter a deployed container just to debug some daemon port bind and running docker commands is pretty slow.

This command should be an alias of something like
```
sudo docker ps
sudo docker exec -it <id> bash
```

### PR DESCRIPTION
**Pull request by josegonzalez**
Add `dokku enter` for connecting to an app container

This command can be used to enter a running container. The following variations of the command exist:

```shell
dokku enter api web
dokku enter api web.1
dokku enter api --container-id ID
```

By default, it runs a `/bin/bash`, but can also be used to run a custom command:

```shell
# just echo hi
dokku enter api web echo hi

# run a long-running command, as one might for a cron task
dokku enter api web python script/background-worker.py
```

Closes #1332

### CODE REVIEW

**Comment by josegonzalez** [comment]
Note: going to merge this in for 0.4.0 to encourage users to upgrade.

**Comment by josegonzalez** [comment]
Refs #450 :)

**Comment by henrik** [comment]
Nice! :thumbsup:

I used [this](https://github.com/dokku-alt/dokku-alt/issues/66#issuecomment-62886633) recently which could be slightly simplified if there was a "dokku enter" that didn't require an app name, but it's very slightly indeed, so probably not worth adding:

```
sudo docker exec CONTAINER_ID su postgres -c "psql db_name -c 'CREATE EXTENSION hstore;'"

# could become

dokku enter --container-id CONTAINER_ID su postgres -c "psql db_name -c 'CREATE EXTENSION hstore;'"
```

Not sure if sudo is required in the one and not the other.

**Comment by josegonzalez** [comment]
I think ensuring we scope the docker call to an app is a good idea, otherwise there is potential for a user to run a command against a container that isn't part of their app.

Of note is that you don't need to specify a container id, or even a running app. You could very well just do:

 ````
# Your procfile can have the following entry:
#
#     background: while true; do foo; sleep 2; done
#
# and `background` scaled to 1
#
# Assumes you only run one background task for an instance
# Will do weird stuff if you have multiple background tasks running

dokku ps:scale api background=1 && dokku enter api background some-command && dokku ps:scale api background=0

# or use a one-off container
dokku --rm run api some-command
```

Assuming you want to have a cron file for your server, here is a potential layout:

```
# API backup cron jobs
MAILTO="mail@example.com"
PATH=/usr/local/bin:/usr/bin:/bin

# m   h   dom mon dow   command
# *   *   *   *   *     command to be executed
# -   -   -   -   -
# |   |   |   |   |
# |   |   |   |   +----- day of week (0 - 6) (Sunday=0)
# |   |   |   +------- month (1 - 12)
# |   |   +--------- day of month (1 - 31)
# |   +----------- hour (0 - 23)
# +----------- min (0 - 59)

### HIGH TRAFFIC TIME IS B/W 00:00 - 04:00 AND 14:00 - 23:59
### RUN YOUR TASKS FROM 04:00 - 14:00
### KEEP SORTED IN TIME ORDER

### PLACE ALL CRON TASKS BELOW

0 0 * * * deploy dokku --rm run api some-command

0 1 * * * dokku ps:scale api background=1 && dokku enter api background some-other-command && dokku ps:scale api background=0

### PLACE ALL CRON TASKS ABOVE, DO NOT REMOVE THE WHITESPACE AFTER THIS LINE

```

^ That should probably be in the documentation, which I'd take as a PR for this PR :)

**Comment by felixyz** [comment]
@josegonzalez I completely fail to see the point of having a dummy background container just so I can `enter` it. Or maybe I missed the point of your example?

**Comment by josegonzalez** [comment]
Its just a way to run a command in a new container that isn't already working. If you set mem/vpu limits on a container, this might be desirable.

**Pull request merged**
