### PR TITLE
Update compatibility version for several plugins

### PR DESCRIPTION
**Pull request by Flink**
As requested in https://github.com/progrium/dokku/issues/1295#issuecomment-136756883

### CODE REVIEW

**Comment by Flink** [comment]
I also cleaned up a little :)

**Comment by josegonzalez** [comment]
Lets use `0.3.26+` instead of just `0.3.26`.

Also, would be ever so lovely if you could test more than just these plugins ;)

**Comment by Flink** [comment]
Ok for `0.3.26+`. For the other plugins, yes but it’ll take some time :grin:. Also we should maybe deprecate some of the plugins listed.

**Comment by josegonzalez** [comment]
For this pr, just change it to `0.3.26+`. You can do deprecations in a different PR, and any other plugins in a separate one as well :)

**Comment by josegonzalez** [comment]
Also note, in a documentation PR update, you can skip tests by adding `[ci skip]` to the commit message.

**Comment by Flink** [comment]
Ah yes you’re right. Ok then!

**Comment by Flink** [comment]
done :)

**Pull request merged**
