### PR TITLE
Support --short flag for the "apps" command.

### PR DESCRIPTION
**Pull request by alessio**
Strip the header out the apps list to make the output machine-parseable.

### CODE REVIEW

**Comment by alessio** [comment]
A shorter one (e.g. -s) would work too as well as grepping $@ for such flag.
Thanks for considering though!

**Comment by josegonzalez** [comment]
Well, should all output be machine parseable? I've been thinking about this for a long time, as my dashboard currently parses the dokku output into something it can use. The more I think about it, the less I like dokku's current bash implementation, as it makes argument parsing a bit weird, and can't be used as a library.

Not really strong on this PR, as I think there are other places where people will want this sort of functionality as well :|

**Comment by alessio** [comment]
Users may appreciate it since AFAICS it's pretty common to use dokku as a component of complex deployment pipelines.

**Comment by alessio** [comment]
I've simplified the command line parsing and replaced the long option with a shorter one (s/--short/-s/)

**Comment by josegonzalez** [comment]
Closing in favor of #949

**Pull request closed without merging**
