### PR TITLE
use ps:restore on instance boot

### PR DESCRIPTION
**Pull request by michaelshobbs**
refs: #1613

### CODE REVIEW

**Comment by josegonzalez** [comment]
Seems legit. Want to test it before I merge?

**Comment by michaelshobbs** [comment]
Want to, no but I will. :smile:

**Comment by michaelshobbs** [comment]
Two apps deployed
```
root@dokku:~/dokku# dokku ls
-----> App Name           Container Type            Container Id              Status
node-js-app2              web                       6c835f94fbd3              running
node-js-app2              worker                    ce800d22e7d3              running
node-js-app               web                       72c34b8893ff              running
node-js-app               worker                    fc8a344f42b3              running
```

One app stopped
```
root@dokku:~/dokku# dokku ps:stop node-js-app2
Stopping node-js-app2 ...
-----> Setting config vars
       DOKKU_APP_RESTORE: 0
root@dokku:~/dokku# dokku ls
-----> App Name           Container Type            Container Id              Status
node-js-app2              web                       6c835f94fbd3              stopped
node-js-app2              worker                    ce800d22e7d3              stopped
node-js-app               web                       72c34b8893ff              running
node-js-app               worker                    fc8a344f42b3              running
```

Reboot:
```
root@dokku:~/dokku# reboot
root@dokku:~/dokku#
Broadcast message from vagrant@dokku
	(/dev/pts/0) at 20:26 ...

The system is going down for reboot NOW!
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Dec  1 20:27:21 2015 from 10.0.2.2
vagrant@dokku:~$ sudo su -
root@dokku:~# dokku ls
-----> App Name           Container Type            Container Id              Status
node-js-app2              web                       90ccbb08272e              stopped
node-js-app2              worker                    d6c9b56c93c8              stopped
node-js-app               web                       90e6eed97cd2              running
node-js-app               worker                    c07ad2d74166              running
```

**Comment by josegonzalez** [comment]
Fucking love it.

**Pull request merged**
