### PR TITLE
Include tip about using sshcommand acl-add

### PR DESCRIPTION
**Pull request by chrisbutcher**
Playing with dokku for the first time in a while, I found that this was a step we could better assist new users through.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Did you use the web installer to add the key? It prompts you for it.

**Comment by chrisbutcher** [comment]
I may have missed something else. I was only seeing 'Welcome to nginx' after install. There was no url provided to get to the installer page.

**Comment by josegonzalez** [comment]
How did you install it?

**Comment by chrisbutcher** [comment]
```
wget https://raw.github.com/progrium/dokku/v0.3.17/bootstrap.sh
sudo DOKKU_TAG=v0.3.17 bash bootstrap.sh
```

**Comment by josegonzalez** [comment]
Gotcha, what host was this on?

**Comment by chrisbutcher** [comment]
Digital Ocean, Ubuntu 14.04x64

**Comment by josegonzalez** [comment]
On digital ocean, there is a ready-made image that should work.

**Pull request merged**
