### PR TITLE
fixes #1270 faulty default container check

### LINKED ISSUE #1270: Killed dokku deploy "$APP"
Can you guys help me out figuring out what's happening?

```
-----> Releasing appname...
-----> Deploying appname...
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> workfolio container output:
       Starting up http-server, serving ./ on: http://0.0.0.0:8080
       Hit CTRL-C to stop the server
=====> end workfolio container output
remote: /usr/local/bin/dokku: line 49: 20781 Killed                  dokku deploy "$APP"
```

### PR DESCRIPTION
**Pull request by kilianc**

### CODE REVIEW

**Comment by michaelshobbs** [comment]
I thought we were doing to use a different method than `grep`... i.e. https://github.com/progrium/dokku/issues/1270#issuecomment-118671446

Honestly I'd prefer dropping all processing of `docker ps` output (considering their [recent change](https://github.com/progrium/dokku/issues/1263)) starting with this one.

**Comment by josegonzalez** [comment]
@kilianc can you update this pr to use the docker command directly?

**Comment by kilianc** [comment]
sure thing

**Comment by kilianc** [comment]
@josegonzalez @michaelshobbs up

**Comment by kilianc** [comment]
test are failing, can you guys look up why? not sure it's me

**Comment by michaelshobbs** [comment]
it looks like its the default container check when i look at the ci output. can you try running the tests locally?

**Comment by kilianc** [comment]
I need to figure out how :) @michaelshobbs

**Comment by kilianc** [comment]
```bash
export DOKKU_APP_CONTAINER_ID=$(docker ps -q --no-trunc | head -1)
echo $DOKKU_APP_CONTAINER_ID

docker top "$DOKKU_APP_CONTAINER_ID" &>/dev/null || echo "App container failed to start $DOKKU_APP_CONTAINER_ID"
docker top "$DOKKU_APP_CONTAINER_ID" &>/dev/null && echo "Container is running $DOKKU_APP_CONTAINER_ID"

docker top "$DOKKU_APP_CONTAINER_ID"a &>/dev/null || echo "App container failed to start $DOKKU_APP_CONTAINER_ID"
docker top "$DOKKU_APP_CONTAINER_ID"a &>/dev/null && echo "Container is running $DOKKU_APP_CONTAINER_ID"
```

this works on my ubuntu

**Comment by michaelshobbs** [comment]
circleci's docker daemon responds with an error ....

```
root@box166:/tmp/config-app# docker top eeaa8d04c65681790d80078e0c01c5c6714b44a4f618f9e4271af4818157de6c
FATA[0000] Error response from daemon: mountpoint for cpu not found
```

**Comment by michaelshobbs** [comment]
`docker inspect -f {{.State.Running}} $CID` works

```
root@box166:/tmp/config-app# docker inspect -f {{.State.Running}}  eeaa8d04c65681790d80078e0c01c5c6714b44a4f618f9e4271af4818157de6c
true
```

for reference:
```
root@box166:/tmp/config-app# docker version
Client version: 1.4.1-circleci
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 1b532d1
OS/Arch (client): linux/amd64
Server version: 1.4.1-circleci
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 1b532d1
```

**Comment by kilianc** [comment]
@michaelshobbs we can use docker inspect but we need to handle "true" "false" and exit code `1` since the container can be stopped, running or not found. docker top was easier

**Comment by kilianc** [comment]
https://github.com/docker/docker/issues/7993 seems a problem with the vm running the test?

**Comment by michaelshobbs** [comment]
i'll hit up circle about the `docker top` issue. seems like `docker inspect` is our only option at the moment if we want tests to pass. (and we do :smile:)

**Comment by kilianc** [comment]
btw I think ps:stop has the same issue. it says the container is stopped when it's running instead

**Comment by michaelshobbs** [comment]
@kilianc were you going to attempt to rework this with `docker inspect`?

**Pull request closed without merging**
