### PR TITLE
Plugins management

### PR DESCRIPTION
**Pull request by Flink**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Uh, rebase?

**Comment by michaelshobbs** [comment]
Wait, what? I thought I was merging this into the plugn branch... What happened here?

**Comment by Flink** [comment]
Hmm I just created a new PR with your branch as its target. Mine was rebased on master.

**Comment by michaelshobbs** [comment]
Ah I totally missed that. I'll need to do this manually as there are many conflicts anyway. Closing this PR.

**Comment by Flink** [comment]
I could try to do a real PR on your branch though

**Pull request closed without merging**
